### ISSUE TITLE
Pdf Loading quite long time in streamlit

### ISSUE THREAD

**Issue by prakash7611** [SonicWarrior1/pdfchat#10]
I have followed the instruction from Readme.

1. Installed Ollama and run Mistral from terminal.
2. Took app.py and ran streamlit command.
3. Browser opened with 8051 port number.
4. Uploaded some random PDF. but spinning for long time "Analysing your document"
5. When i analyse the code, i see ollama port number and persist path for chroma db is jj. 
6. Ollama running in 11434 port
7. Did i miss Anything

**Comment by SonicWarrior1** [comment]
Have you tried any other pdf file or it is occurring for one only ? maybe the file could be large that it takes long time 
and the jj directory should be made automatically once the file is analysed

**Comment by deepakitkar** [comment]
I tried a couple of different pdf files and it doesn't go beyond "Analyzing your document". The least size of PDF I used was 98kb. On the Ollama end, I see this -
"time=2024-07-02T17:05:00.678+05:30 level=INFO source=server.go:599 msg="llama runner started in 2.69 seconds"
[GIN] 2024/07/02 - 17:11:16 | 200 |         6m18s |       127.0.0.1 | POST     "/api/embeddings""
Any idea?

**Comment by PrakashN73** [comment]
Ollama requires good System specification and GPU else to process 10kb file it would take 30 min and to get a response it will take another 20 minutes. @SonicWarrior1 works like a charm on good specification system

**Comment by SonicWarrior1** [comment]
> I tried a couple of different pdf files and it doesn't go beyond "Analyzing your document". The least size of PDF I used was 98kb. On the Ollama end, I see this - "time=2024-07-02T17:05:00.678+05:30 level=INFO source=server.go:599 msg="llama runner started in 2.69 seconds" [GIN] 2024/07/02 - 17:11:16 | 200 | 6m18s | 127.0.0.1 | POST "/api/embeddings"" Any idea?

Based on the log you provided, it seems that Ollama is functioning correctly, as it returns a status code 200. The extended processing time might be due to your system specifications. Could you please share your system specifications?
