### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by ojuschugh1** [SonicWarrior1/pdfchat#9]
Hi 

I tried to run this program as you told in the readme.

Since I am a Windows user so, I ran via wsl2.

I ran the ollama and mistral both in the wsl2 and I also ran this project in the wsl2. Everything worked but when I uploaded the pdf, and asked what is this pdf or file about.

It gives the following error -:

> `Prompt -: Hi kindly summarize the above pdf

> ChatBot -: I'd be happy to help you understand the content of a PDF file, but I'll need you to provide the essential details about it first. Could you please specify the title or topic of the PDF, and if possible, its main points or arguments? This will allow me to give you an accurate and professional summary. However, as a helpful chatbot, I cannot directly access or read files without your assistance, including a provided link or  attachment.`

Could you please guide me what is the issue? 

Thanks and Regards

**Comment by SonicWarrior1** [comment]
check the the terminal where code is running it shows the context which llm is taking for refference and see if its picking up file contents there or not

**Comment by loveStudyWjj** [comment]
> Hi
> 
> I tried to run this program as you told in the readme.
> 
> Since I am a Windows user so, I ran via wsl2.
> 
> I ran the ollama and mistral both in the wsl2 and I also ran this project in the wsl2. Everything worked but when I uploaded the pdf, and asked what is this pdf or file about.
> 
> It gives the following error -:
> 
> > `Prompt -: Hi kindly summarize the above pdf
> 
> > ChatBot -: I'd be happy to help you understand the content of a PDF file, but I'll need you to provide the essential details about it first. Could you please specify the title or topic of the PDF, and if possible, its main points or arguments? This will allow me to give you an accurate and professional summary. However, as a helpful chatbot, I cannot directly access or read files without your assistance, including a provided link or  attachment.`
> 
> Could you please guide me what is the issue?
> 
> Thanks and Regards

![image](https://github.com/SonicWarrior1/pdfchat/assets/97963711/20892e5c-5d94-4078-9eff-1c960663578c)

You can try removing ".pdf"

**Comment by ojuschugh1** [comment]
Thanks  @SonicWarrior1  @loveStudyWjj  , I found the error it was due to permission denial in WSL2 Linux to read the files.
